- alias: Turn on Coffee Machine
  initial_state: true
  trigger:
    platform: time
    at: '06:15:00'
  condition:
    condition: time
    weekday:
    - 'mon'
    - 'tue'
    - 'wed'
    - 'thu'
    - 'fri'
  action:
    service: switch.turn_on
    entity_id:
    - switch.coffee

- alias: Turn on Coffee Machine WE
  initial_state: true
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: time
    weekday:
    - 'sat'
    - 'sun'
  action:
    service: switch.turn_on
    entity_id:
    - switch.coffee

- alias: Turn off Coffee Machine
  initial_state: true
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
    - 'mon'
    - 'tue'
    - 'wed'
    - 'thu'
    - 'fri'
  action:
    service: switch.turn_off
    entity_id:
    - switch.coffee

- alias: Turn off Coffee Machine WE
  initial_state: true
  trigger:
    platform: time
    at: '09:45:00'
  condition:
    condition: time
    weekday:
    - 'sat'
  action:
    service: switch.turn_off
    entity_id:
    - switch.coffee

- alias: Turn on Outside light
  initial_state: true
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: time
    before: '21:00:00'
  action:
    service: switch.turn_on
    entity_id:
    - switch.outdoor_light
    - switch.outdoor_christmas

- alias: Turn off Outside light
  initial_state: true
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: switch.turn_off
    entity_id:
    - switch.outdoor_light
    - switch.outdoor_christmas

- alias: Turn on Christmas tree light
  initial_state: true
  trigger:
  - platform: time
    at: '06:00:00'
  - platform: time
    at: '16:00:00'
  action:
    service: switch.turn_on
    entity_id:
    - switch.indoor_christmas

- alias: Turn off Christmas light
  initial_state: true
  trigger:
  - platform: time
    at: '09:00:00'
  - platform: time
    at: '22:00:00'
  action:
    service: switch.turn_off
    entity_id:
    - switch.indoor_christmas

- alias: 'Auto Renew SSL Cert'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl
