- alias: Turn on Coffee Machine
  initial_state: true
  trigger:
    platform: time
    at: '06:15:00'
  condition:
    condition: time
    weekday:
    - 'mon'
    - 'tue'
    - 'wed'
    - 'thu'
    - 'fri'
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_coffee

- alias: Turn on Coffee Machine WE
  initial_state: true
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: time
    weekday:
    - 'sat'
    - 'sun'
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_coffee

- alias: Turn off Coffee Machine
  initial_state: true
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
    - 'mon'
    - 'tue'
    - 'wed'
    - 'thu'
    - 'fri'
  action:
    service: switch.turn_off
    entity_id: switch.kitchen_coffee

- alias: Turn off Coffee Machine WE
  initial_state: true
  trigger:
    platform: time
    at: '09:45:00'
  condition:
    condition: time
    weekday:
    - 'sat'
  action:
    service: switch.turn_off
    entity_id: switch.kitchen_coffee

- alias: Turn on Outside light
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: '+00:30:00'
  condition:
    condition: time
    before: '21:00:00'
  action:
    service: switch.turn_on
    entity_id:
    - switch.garden
    - switch.outddor_christmas

- alias: Turn off Outside light
  initial_state: true
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: switch.turn_off
    entity_id:
    - switch.garden
    - switch.outddor_christmas


