homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.319641
  longitude: -122.054298
  unit_system: imperial
  elevation: 236
  country: US
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  external_url: "https://g1grignou.us.to"
  internal_url: "http://mascot.g1grignou.us.to:8123"
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
    - 192.168.1.0/24
  - type: legacy_api_password
    api_password: !secret api_password

# Not used anymore - moved to UI
# weather:
#   - platform: pirateweather
#     api_key: 960791c75c0a8e6fa3188d8de8465930
#     # Additional optional values:
#     latitude: 37.319641
#     longitude: -122.054298
#     mode: "hourly"
#     name: HomeWeather

mobile_app:

system_health:
          
sun:

http:
  ssl_certificate: /etc/letsencrypt/live/g1grignou.us.to/fullchain.pem
  ssl_key: /etc/letsencrypt/live/g1grignou.us.to/privkey.pem

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

recorder:

# nest:
#   client_id: !secret nest_product_id
#   client_secret: !secret nest_product_secret

# climate:
#    platform: nest

#vemono:
#  host:
#  - hifipwr
#  - coffeepwr

mqtt:
#  embedded:
#    listeners:
#        default:
#            max-connections: 50
#            type: tcp
#            bind: 0.0.0.0:8081
#            ssl: 'on'
#            certfile: /home/pi/ssl/server.10y.crt
#            keyfile: /home/pi/ssl/server.10y.key
#    timeout-disconnect-delay: 2
#    auth:
#            #plugins: ['auth_file']
#        plugins: ['auth_anonymous']
#        allow-anonymous: false
#        password-file: /home/pi/.homeassistant/mqtt/password
#    topic-check:
#        enabled: True
#        plugins: 
#          - topic_taboo
  #certificate: /home/pi/ssl/server.10y.crt
  sensor:
  - name: "10232 Netmeter"
    unique_id: "10232-energey-power"
    state_topic: "10232/energy/demand"
    state_class: measurement
    device_class: power
    unit_of_measurement: kW
    value_template: '{{ value_json.val }}'
  
  - name: "10232 Netmeter Delivered"
    unique_id: "10232-energey-delivered"
    state_topic: "10232/energy/delivered"
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    value_template: '{{ value_json.val }}'
  
  - name: "10232 Netmeter Received"
    unique_id: "10232-energey-received"
    state_topic: "10232/energy/received"
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    value_template: '{{ value_json.val }}'
  
  - name: "10232 Solar"
    state_topic: "solar/energy/solarcity"
    state_class: measurement
    device_class: power
    unit_of_measurement: W
    value_template: '{{ value_json.power }}'
  
  - name: "10232 Solar Voltage"
    state_topic: "solar/energy/solarcity"
    state_class: measurement
    device_class: voltage
    unit_of_measurement: V
    value_template: '{{ value_json.voltage | multiply(0.1) }}'
  
  - name: "10238 Netmeter"
    unique_id: "10238-energey-power"
    state_topic: "10238/energy/demand"
    state_class: measurement
    device_class: power
    unit_of_measurement: kW
    value_template: '{{ value_json.val }}'
  
  - name: "10238 Netmeter Delivered"
    unique_id: "10238-energey-delivered"
    state_topic: "10238/energy/delivered"
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    value_template: '{{ value_json.val }}'
  
  - name: "10238 Netmeter Received"
    unique_id: "10238-energey-received"
    state_topic: "10238/energy/received"
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    value_template: '{{ value_json.val }}'



# deprecated
# cast:

# deprecated
# rachio:
#  api_key: !secret rachio_api_key

amcrest:
  host: frontgarage
  username: admin
  password: !secret amcrest_passowrd
  scan_interval: 60

#logger: 
#  default: warn
#  logs:
#          components.mqtt: debug
google_assistant:
  project_id: homeassistant-285504
  service_account: !include homeassistant-285504-33956d45990c.json
  report_state: true
  exposed_domains:
    - switch

stream:

shell_command:
  renew_ssl: certbot renew --quiet --no-self-upgrade --standalone --preferred-challenges tls-sni-01 --tls-sni-01-port 8123 --pre-hook "sudo systemctl stop home-assistant@homeassistant.service" --post-hook "sudo systemctl start home-assistant@homeassistant.service"

energy:

automation: !include automations.yaml
media_player: !include devices/media_player.yaml
sensor: !include devices/sensor.yaml
camera: !include devices/camera.yaml
command_line: !include devices/switch.yaml
script: !include script.yaml
group: !include group.yaml
panel_iframe: !include panel.yaml

