homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.3042
  longitude: -122.0946
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

sun:

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# Discover some devices automatically
discovery:

nest:
  username: <redacted>
  password: <redacted>

apcupsd:
  host: hippobeach

thermostat:
  platform: nest

mqtt:
  embedded:
    listeners:
        default:
            max-connections: 50
            type: tcp
            bind: 0.0.0.0:8081
            ssl: 'on'
            certfile: /home/pi/ssl/server.crt
            keyfile: /home/pi/ssl/server.key
    timeout-disconnect-delay: 2
    auth:
        plugins: ['auth_file']
        allow-anonymous: false
        password-file: /home/pi/.homeassistant/mqtt/password
  broker: mascot
  port: 8081
  client_id: home-assistant-1
  keepalive: 60
  username: <redacted>
  password: <redacted>
  certificate: /home/pi/ssl/server.crt
  protocol: 3.1.1


automation: !include automation.yaml
media_player: !include devices/media_player.yaml
sensor: !include devices/sensor.yaml
binary_sensor: !include devices/binary_sensor.yaml
switch: !include devices/switch.yaml
#scene: !include scene.yaml
script: !include script.yaml
group: !include group.yaml

