homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.319641
  longitude: -122.054298
  unit_system: imperial
  elevation: 236
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

sun:

http:
  api_password: !secret api_password

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# Discover some devices automatically
discovery:

recorder:

device_tracker:
  - platform: owntracks

nest:
  client_id: !secret nest_product_id
  client_secret: !secret nest_product_secret

apcupsd:
  host: localhost

climate:
  platform: nest

vemono:
  host:
  - hifipwr
  - coffeepwr

mqtt:
#  embedded:
#    listeners:
#        default:
#            max-connections: 50
#            type: tcp
#            bind: 0.0.0.0:8081
#            ssl: 'on'
#            certfile: /home/pi/ssl/server.10y.crt
#            keyfile: /home/pi/ssl/server.10y.key
#    timeout-disconnect-delay: 2
#    auth:
#            #plugins: ['auth_file']
#        plugins: ['auth_anonymous']
#        allow-anonymous: false
#        password-file: /home/pi/.homeassistant/mqtt/password
#    topic-check:
#        enabled: True
#        plugins: 
#          - topic_taboo
  broker: mascot
  port: 8081
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /home/pi/ssl/server.10y.crt
  protocol: 3.1.1
  discovery: true

cast:

tesla:
  username: gwendal@gmail.com
  password: !secret tesla_password

tplink:
  discovery: true

amcrest:
  host: frontgarage
  username: admin
  password: !secret amcrest_passowrd
  scan_interval: 60
  sensors:
      sdcard

#logger: 
#  default: warn
#  logs:
#          components.mqtt: debug

automation: !include automation.yaml
media_player: !include devices/media_player.yaml
sensor: !include devices/sensor.yaml
camera: !include devices/camera.yaml
binary_sensor: !include devices/binary_sensor.yaml
switch: !include devices/switch.yaml
#scene: !include scene.yaml
script: !include script.yaml
group: !include group.yaml

