- name: Forecast
  platform: darksky
  api_key: 960791c75c0a8e6fa3188d8de8465930
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - apparent_temperature

- platform: apcupsd
  resources:
    - linev
    - loadpct
    - timeleft

- name: "10232 TED"
  platform: ted5000
  host: ted5000

- platform: integration
  source: sensor.house_solar_power
  name: tesla_solar_panels_kwh
  unit_prefix: k
  unit_time: h
  method: left
  round: 2

- platform: integration
  source: sensor.10232_ted_mtu1_power
  name: home_indoor_kwh
  unit_prefix: k
  unit_time: h
  round: 2

# - platform: plex
#   host: ggnas
#   token: "5yw4eHrpkZmufBbkbvjV"

- platform: amcrest

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/g1grignou.us.to/cert.pem | awk '{ print $NF }'"
