# Prediction of weather
- platform: yr
  monitored_conditions:
    - temperature
    - windDirection

- name: Forecast
  platform: forecast
  api_key: 960791c75c0a8e6fa3188d8de8465930
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - apparent_temperature

- name: Router UPS
  platform: apcupsd
  resources:
    - linev
    - loadpct
    - timeleft

- platform: nest
  monitored_conditions:
    - 'temperature'
    - 'target'

- name: "10232 Netmeter"
  platform: mqtt
  state_topic: "10232/energy/demand"
  qos: 0
  unit_of_measurement: "W"
  value_template: '{{ value_json.val | multiply(1000) }}'

- name: "10238 Netmeter"
  platform: mqtt
  state_topic: "10238/energy/demand"
  qos: 0
  unit_of_measurement: "W"
  value_template: '{{ value_json.val | multiply(1000) }}'

- name: "10232"
  platform: ted5000
  host: ted5000
  resources:
  - power.mtu1
  - voltage.mtu1

- platform: ohmconnect
  id: D2Ve7lR3
