- platform: command_line
  switches:
    subwoofer:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 2 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 2 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 2

    projector:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 1 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 1 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 1

    q:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 3 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 3 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 3

    player:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 4 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 4 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 4

    amplifier:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 5 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 5 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 5

    monitor:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 6 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 6 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 6

    dvd:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 7 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 7 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 7

    mascot:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 8 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 8 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 8

    ggnas:
      command_on: /usr/local/sbin/ipmi_set.sh 192.168.1.142 on
      command_off: /usr/local/sbin/ipmi_set.sh 192.168.1.142 off
      command_state: /usr/local/sbin/ipmi_get.sh 192.168.1.142

- platform: tplink
  name: garden
  host: 192.168.1.62

- platform: tplink
  name: christmas
  host: 192.168.1.61

- platform: tplink
  name: outdoor_christmas
  host: 192.168.1.65
