- platform: command_line
  switches:
    projector:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 6 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 6 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 6

    player:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 5 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 5 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 5

    amplifier:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 8 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 8 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 8

    monitor:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 3 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 3 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 3

    dvd:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 2 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 2 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 2

    mascot:
      command_on: /usr/local/sbin/apc_set.sh apcgwen 1 1
      command_off: /usr/local/sbin/apc_set.sh apcgwen 1 2
      command_state: /usr/local/sbin/apc_get.sh apcgwen 1

    ggnas:
      command_on: /usr/local/sbin/ipmi_set.sh ggnas_cons on
      command_off: /usr/local/sbin/ipmi_set.sh ggnas_cons off
      command_state: /usr/local/sbin/ipmi_get.sh ggnas_cons

- platform: tplink
  name: garden
  host: 192.168.1.62

- platform: tplink
  name: subwoofer
  host: 192.168.1.61

- platform: tplink
  name: outdoor_christmas
  host: 192.168.1.65
